// src/components/calendar/CalendarHeader.vue
<template>
  <div class="flex items-center gap-4">
    <button
      v-for="viewType in viewTypes"
      :key="viewType.type"
      class="inline-flex items-center gap-2 px-3 py-2 rounded-md text-sm font-medium transition-colors"
      :class="[
        modelValue === viewType.type
          ? 'bg-primary text-primary-foreground'
          : 'hover:bg-muted'
      ]"
      @click="$emit('update:modelValue', viewType.type)"
    >
      <component :is="viewType.icon" class="h-4 w-4" />
      <span>{{ viewType.label }}</span>
    </button>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { Calendar, CalendarDays, CalendarRange } from 'lucide-vue-next';
import type { CalendarView } from '@/types/index';

const props = defineProps<{
  modelValue: CalendarView['type'];
}>();

const emit = defineEmits<{
  'update:modelValue': [value: CalendarView['type']];
}>();

const viewTypes = [
  { type: 'day' as const, label: 'Jour', icon: Calendar },
  { type: 'week' as const, label: 'Semaine', icon: CalendarDays },
  { type: 'month' as const, label: 'Mois', icon: CalendarRange },
];
</script>

// components/calendar/calendar-header.tsx
'use client';

import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { CalendarView } from '@/app/types';
import { Calendar, CalendarDays, CalendarRange } from 'lucide-react';

interface CalendarHeaderProps {
  view: CalendarView;
  onViewChange: (view: CalendarView) => void;
}

const views = [
  {
    type: 'day',
    label: 'Jour',
    icon: Calendar,
  },
  {
    type: 'week',
    label: 'Semaine',
    icon: CalendarDays,
  },
  {
    type: 'month',
    label: 'Mois',
    icon: CalendarRange,
  },
] as const;

export function CalendarHeader({ view, onViewChange }: CalendarHeaderProps) {
  const currentView = views.find((v) => v.type === view.type);
  const Icon = currentView?.icon || Calendar;

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" className="gap-2">
          <Icon className="h-4 w-4" />
          {currentView?.label}
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        {views.map((v) => (
          <DropdownMenuItem
            key={v.type}
            onClick={() => onViewChange({ type: v.type, date: view.date })}
          >
            <v.icon className="mr-2 h-4 w-4" />
            {v.label}
          </DropdownMenuItem>
        ))}
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
