// src/components/calendar/TaskDialog.vue
<template>
  <Dialog v-model="isOpen">
    <div class="flex flex-col gap-4">
      <div class="flex flex-col gap-1">
        <h2 class="text-lg font-semibold">Nouvelle tâche</h2>
        <p class="text-sm text-muted-foreground">
          {{ formattedDate }}
        </p>
      </div>
      <form @submit.prevent="handleSubmit" class="space-y-4">
        <div class="space-y-2">
          <label class="text-sm font-medium">Titre</label>
          <input
            v-model="form.title"
            type="text"
            class="w-full px-3 py-2 rounded-md border bg-background"
            placeholder="Titre de la tâche"
            required
          />
        </div>
        <div class="space-y-2">
          <label class="text-sm font-medium">Équipe</label>
          <select
            v-model="form.teamId"
            class="w-full px-3 py-2 rounded-md border bg-background"
            required
          >
            <option value="" disabled>Sélectionner une équipe</option>
            <option
              v-for="team in teams"
              :key="team.id"
              :value="team.id"
            >
              {{ team.name }}
            </option>
          </select>
        </div>
        <div class="space-y-2">
          <label class="text-sm font-medium">Durée (minutes)</label>
          <input
            v-model.number="form.duration"
            type="number"
            min="15"
            max="480"
            step="15"
            class="w-full px-3 py-2 rounded-md border bg-background"
            required
          />
        </div>
        <div class="space-y-2">
          <label class="text-sm font-medium">Lieu</label>
          <input
            v-model="form.location"
            type="text"
            class="w-full px-3 py-2 rounded-md border bg-background"
            placeholder="Lieu (optionnel)"
          />
        </div>
        <div class="flex justify-end gap-2">
          <button
            type="button"
            class="px-4 py-2 rounded-md hover:bg-muted"
            @click="isOpen = false"
          >
            Annuler
          </button>
          <button
            type="submit"
            class="px-4 py-2 rounded-md bg-primary text-primary-foreground hover:bg-primary/90"
          >
            Créer
          </button>
        </div>
      </form>
    </div>
  </Dialog>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { format } from 'date-fns';
import { fr } from 'date-fns/locale';
import Dialog from '@/components/ui/Dialog.vue';
import type { Task, Team } from '@/types/index';

const props = defineProps<{
  startDate: Date;
  teams: Team[];
}>();

const emit = defineEmits<{
  'submit': [task: Partial<Task>];
}>();

const isOpen = ref(false);

const formattedDate = computed(() => 
  format(props.startDate, 'EEEE d MMMM yyyy à HH:mm', { locale: fr })
);

const form = ref({
  title: '',
  teamId: '',
  duration: 60,
  location: '',
});

const handleSubmit = () => {
  const endDate = new Date(props.startDate);
  endDate.setMinutes(endDate.getMinutes() + form.value.duration);

  emit('submit', {
    ...form.value,
    startDate: props.startDate.toISOString(),
    endDate: endDate.toISOString(),
  });

  // Reset form and close dialog
  form.value = {
    title: '',
    teamId: '',
    duration: 60,
    location: '',
  };
  isOpen.value = false;
};

// Expose open method
defineExpose({
  open: () => {
    isOpen.value = true;
  },
});
</script>

// components/calendar/task-dialog.tsx
'use client';

import * as React from 'react';
import { format } from 'date-fns';
import { fr } from 'date-fns/locale';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Task, Team } from '@/app/types';

const taskSchema = z.object({
  title: z.string().min(1, 'Le titre est requis'),
  teamId: z.string().min(1, "L'équipe est requise"),
  duration: z.coerce.number().min(15, 'Minimum 15 minutes').max(480, 'Maximum 8 heures'),
  location: z.string().optional(),
});

interface TaskDialogProps {
  startDate: Date;
  teams: Team[];
  onSubmit: (data: Partial<Task>) => Promise<void>;
}

export function TaskDialog({ startDate, teams, onSubmit }: TaskDialogProps) {
  const [open, setOpen] = React.useState(false);

  const form = useForm<z.infer<typeof taskSchema>>({
    resolver: zodResolver(taskSchema),
    defaultValues: {
      title: '',
      duration: 60,
      location: '',
    },
  });

  const handleSubmit = async (data: z.infer<typeof taskSchema>) => {
    try {
      const endDate = new Date(startDate);
      endDate.setMinutes(endDate.getMinutes() + data.duration);

      await onSubmit({
        ...data,
        startDate: startDate.toISOString(),
        endDate: endDate.toISOString(),
        status: 'scheduled',
      });

      setOpen(false);
      form.reset();
    } catch (error) {
      console.error('Error creating task:', error);
    }
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm">
          Nouvelle tâche
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Créer une tâche</DialogTitle>
          <DialogDescription>
            {format(startDate, 'EEEE d MMMM yyyy à HH:mm', { locale: fr })}
          </DialogDescription>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(handleSubmit)} className="space-y-4">
            <FormField
              control={form.control}
              name="title"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Titre</FormLabel>
                  <FormControl>
                    <Input placeholder="Titre de la tâche" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="teamId"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Équipe</FormLabel>
                  <Select onValueChange={field.onChange} defaultValue={field.value}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Sélectionner une équipe" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      {teams.map((team) => (
                        <SelectItem key={team.id} value={team.id}>
                          {team.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="duration"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Durée (minutes)</FormLabel>
                  <FormControl>
                    <Input type="number" min={15} max={480} step={15} {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <FormField
              control={form.control}
              name="location"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Lieu</FormLabel>
                  <FormControl>
                    <Input placeholder="Lieu (optionnel)" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <DialogFooter>
              <Button type="submit">Créer</Button>
            </DialogFooter>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}
